# SwiftLint configuration for Cluster Headache Tracker iOS

# Paths to include/exclude
included:
  - Cluster Headache Tracker
  - Cluster Headache TrackerTests
  - Cluster Headache TrackerUITests

excluded:
  - build
  - Pods
  - Carthage
  - ${PWD}/build
  - ${PWD}/DerivedData
  - ${PWD}/.build
  - ${PWD}/.swiftpm
  - ${PWD}/Package.swift
  - ${PWD}/*/Package.swift
  - ${PWD}/*/*/Package.swift
  - ${PWD}/*/*/*/Package.swift
  - ${PWD}/*/*/*/*/Package.swift

# Rule configuration
disabled_rules:
  - trailing_comma
  - todo
  - force_unwrapping
  - object_literal
  - attributes
  - for_where
  - unused_enumerated
  - empty_xctest_method

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Rule parameters
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

cyclomatic_complexity:
  warning: 15
  error: 20

# Custom rules
custom_rules:
  no_force_try:
    name: "Avoid force try"
    regex: 'try!'
    message: "Use proper error handling instead of force try"
    severity: error
    
  no_hardcoded_strings:
    name: "Avoid hardcoded strings"
    regex: '(case|return|let|var)\s+"[^"]{20,}"'
    message: "Consider using localized strings for user-facing text"
    severity: warning
    match_kinds:
      - keyword
      - string

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
