#!/bin/bash

# This script loads environment variables from .env file or CI/CD environment
# and generates a Swift configuration file

# Set the output file path
OUTPUT_FILE="${SRCROOT}/Cluster Headache Tracker/Generated/EnvironmentConfig.swift"

# Create the Generated directory if it doesn't exist
mkdir -p "${SRCROOT}/Cluster Headache Tracker/Generated"

# Check if .env file exists and source it (for local development)
if [ -f "${SRCROOT}/.env" ]; then
    export $(cat "${SRCROOT}/.env" | grep -v '^#' | xargs)
fi

# Get the Honeybadger API key from environment variable
HONEYBADGER_API_KEY="${HONEYBADGER_API_KEY:-}"

# Generate the Swift file
cat > "$OUTPUT_FILE" << EOF
// This file is auto-generated by the build script. Do not edit manually.
// Generated on $(date)

import Foundation

enum EnvironmentConfig {
    static let honeybadgerAPIKey: String? = $(if [ -z "$HONEYBADGER_API_KEY" ]; then echo "nil"; else echo "\"$HONEYBADGER_API_KEY\""; fi)
}
EOF

echo "Environment configuration generated at $OUTPUT_FILE"
